### PR TITLE
Compare codex-africanus predict vs meqtrees

### PR DESCRIPTION
**Pull request by sjperkins**
- [x] Tests added / passed

  ```bash
  $ py.test -v -s africanus
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i africanus
  $ flake8 africanus
  $ pycodestyle africanus
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
@paoloserra This PR started testing the `radec_to_lm` conversion vs astropy to ensure they agree. 

I extended it to add an end-to-end test comparing the codex-africanus predict against meqtrees. They also agree once one takes [sign conventions](https://github.com/ska-sa/codex-africanus/pull/79/commits/4d04bdc8d0e4d8d49ca3edec36ce3dfb813df55c) into account, but I've been told that this shouldn't matter for the purposes of imaging. The script does have a `--invert-uvw` command now to facilitate this.

I've also updated the predict script to automatically take the correlation types associated with each `DATA_DESC_ID` into account so one shouldn't need to manually specify linear/circular feeds any longer.

I'm going to merge this PR now. Let us know whether the predict is successful for your subtraction purposes.

**Comment by paoloserra** [comment]
Thanks @sjperkins , this worked very well.

I've had to use the -iuvw option to place the model components at the correct Ra,Dec.

I've tested it both for a single source and for a collection of flat-spectrum, unpolarised sources. It did everything correctly.

I will now implement more complex model spectral shapes based on the WSclean output.

**Comment by sjperkins** [comment]
> Thanks @sjperkins , this worked very well.

Cool, one thing you might try is setting the row_chunk and source_chunk sizes higher. This will probably increase your core usage at the expensive of increasing memory -- there's a tradeoff here.

> I've had to use the -iuvw option to place the model components at the correct Ra,Dec.

Hmmmm, I did not expect you would have to use this option to get the correctt results. I should probably do some more investigation here as I would like everything to "*just work*".

Let me know if Gaussian Shape parameters would be useful for you because I think they are easy to add.

**Comment by paoloserra** [comment]
> Let me know if Gaussian Shape parameters would be useful for you because I think they are easy to add.

Yes they would be. In some fields we must use multi-scale clean. The model will then include Gaussian components.

**Pull request merged**
