### PR TITLE
Fix kaiser bessel filter and taper

### PR DESCRIPTION
**Pull request by sjperkins**
- Fix Kaiser Bessel filter by multiplying through by the `sinc` function.
- Numerically compute the taper of the Kaiser Bessel.
- Add plot-filter and plot-taper command-line utilities.

- [x] Tests added / passed

  ```bash
  $ py.test -v -s africanus
  ```

  If the pycodestyle tests fail, the quickest way to correct
  this is to run `autopep8` and then `pycodestyle` to fix the
  remaining issues.

  ```
  $ pip install -U autopep8 pycodestyle
  $ autopep8 -r -i africanus
  $ pycodestyle africanus
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
@landmanbester She's all yours

**Comment by landmanbester** [comment]
Ok so I have been testing both the simple gridder and the degridder against the DFT (which I am pretty sure of because it agrees with Meqtrees). Here is the fractional difference between two dirty images obtained from random visibilities and uv-coverages with w set to zero

dirty_diff

For the degridder I get a max difference of 1e-6 for a point source at the centre and it gets worse as I move it away from the centre. The script I used to compare the two is [here](https://github.com/landmanbester/codex-africanus/blob/fix-kaiser-bessel-filter-and-taper/africanus/gridding/simple/tests/gridder_vs_dft.py). Any thoughts on what could be causing this @bennahugo @o-smirnov? Looks like it might be the taper but not sure how since I'm using the standard formula for the Kaiser Bessel taper

**Comment by landmanbester** [comment]
This definitely has something to do with how the filter/taper is being applied. Here is the difference if I make both the oversampling and support even

dirty_diff_even

Seems to make it worse in the opposit direction....

**Comment by sjperkins** [comment]
@landmanbester I can't offer much input on the discrepancy between the DFT and the gridder/degridder. However, I do want to say that the `test_forward_operator` and `test_backward_operator` tests are a good axiom for any future gridders in codex.

**Pull request merged**
