### PR TITLE
Add hessian function and double accumulation option to gridder

### PR DESCRIPTION
**Pull request by landmanbester**
* adds a paranoid mode to the gridder to avoid accumulation errors when gridding in single precision. 
* adds the Hessian function (out of memory and in place) R.H W R to wgridder.

### CODE REVIEW

**Comment by landmanbester** [comment]
Alright, ready for you when you have a sec @sjperkins. As discussed I haven't included any faceting capabilities in this PR

**Review by sjperkins — COMMENTED** [review]
Looks good to me. Do you think its worth adding test cases for this functionality?

**Comment by landmanbester** [comment]
Yes, definitely. I was just trying to come up with a good test for the functionality that won't add too much to the runtime. I think I might have just thought of one. Let's hold off for a bit before merging

**Comment by landmanbester** [comment]
Alright, I have added a test for double accumulation while simultaneously testing that hessian produces the dirty image when acting on the model. There is only a single parametrisation for the test because it takes a while (need a large number of rows to test double accumulation). Note that the hessian function allows us to compute residual images as

IR = ID - hessian(x)

where, since the hessian doesn't require visibilities, we have effectively reduced the IO by two thirds (only need to read in (assumed fixed) real valued weights).

**Comment by sjperkins** [comment]
In! thanks @landmanbester  and @mreineck

**Pull request merged**
