### PR TITLE
Make predict_vis docstrings consistent

### PR DESCRIPTION
**Pull request by sjperkins**
- [x] Tests added / passed

  ```bash
  $ py.test -v -s africanus
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i africanus
  $ flake8 africanus
  $ pycodestyle africanus
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
@JSKenyon Could you please take a look a the changes and see if they make sense? One issue is that the "base coherencies" is still called **base_vis** but I don't want to rename it throughout the code base.

**Comment by JSKenyon** [comment]
I actually think that the it is the base part of base visibilities that is confusing. If I understood correctly, the matrix B is almost an implementation detail - it expresses the fact that we may accumulate single visibility over a chunked source dimension. In the limit where there is no need to chunk over the source dimension I think that the B matrix becomes unnecessary/zero. Perhaps precomputed visibilities would be a more sensible name. That would also suggest the use case in which B contains model visibilities obtained from another source e.g. a MODEL_DATA column.

**Comment by sjperkins** [comment]
> I actually think that the it is the base part of base visibilities that is confusing. If I understood correctly, the matrix B is almost an implementation detail - it expresses the fact that we may accumulate single visibility over a chunked source dimension. 

Indeed, that is its purpose, but I think the term "coherencies" expresses that which is accumulated more accurately as the DIE terms are not yet applied and would presumably create the wrong result if they were.

> In the limit where there is no need to chunk over the source dimension I think that the B matrix becomes unnecessary/zero. 

Yes

> Perhaps precomputed visibilities would be a more sensible name. That would also suggest the use case in which B contains model visibilities obtained from another source e.g. a MODEL_DATA column.

Is this not a different case as the DIE's have not yet been applied? Something iike:

```python
ds.MODEL_DATA + predict_vis(...)
```

**Comment by JSKenyon** [comment]
As we discussed at lunch, I think base is the misleading term - feel free to settle on an alternative.

**Pull request merged**
