### PR TITLE
Optimise summation in coherency jones multiply sum

### PR DESCRIPTION
**Pull request by sjperkins**
- Previously used array slicing.
- Explicit indexing is now used.

- [x] Tests added / passed

  ```bash
  $ py.test -v -s africanus
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i africanus
  $ flake8 africanus
  $ pycodestyle africanus
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
@o-smirnov @paoloserra @JSKenyon Here's the slowdown in the predict.

Beware all who don't explicitly index their arrays... /cc @landmanbester 

I'm seeing a factor of between 8 and 16 speedup on predict_vis with this change with pytest-benchmark. Expect more when numba 0.46 is released with function inlining support.

**Comment by paoloserra** [comment]
The factor 8-16 caught my eye... As far as https://github.com/paoloserra/crystalball is concerned this is just a matter of upgrading to the latest codex?

**Comment by sjperkins** [comment]
It's only in master branch for the moment. Note that the next release will
be python 3 only.

**Comment by JSKenyon** [comment]
@sjperkins Just tried it out - [I feel this is appropriate.](https://youtu.be/StTqXEQ2l-Y)

**Comment by sjperkins** [comment]
Hi @paoloserra. I saw your email and you've definitely spotted something. I've reworked the benchmarking script in https://github.com/ska-sa/codex-africanus/pull/159#issuecomment-548283142 to try to reproduce the benchmark for my claims in https://github.com/ska-sa/codex-africanus/pull/143#issuecomment-526231476. Regrettably, at this point (on numba 0.43.1) the difference is negligible and I'm ready to eat my hat, unless @JSKenyon wants to prevent me from doing so because I think he confirmed the speedup on one of the Rhodes servers.

I'll drill into this more tomorrow.

Here is the script:

```python
import numpy as np
from africanus.rime.predict import predict_vis


def rf(*a, **kw):
    return np.random.random(*a, **kw)


def rc(*a, **kw):
    return rf(*a, **kw) + 1j*rf(*a, **kw)


def test_benchmark_predict_vis(benchmark):
    s = 10
    t = 100
    a = 14
    c = 64
    co = (2, 2)

    ant1, ant2 = (ar.astype(np.int32) for ar in np.triu_indices(a, 1))
    bl = ant1.shape[0]
    r = t * bl

    a1j = a2j = rc((s, t, a, c) + co)
    blj = rc((s, r, c) + co)
    # g1j = g2j = rc((t, a, c) + co)
    bvis = rc((r, c) + co)

    print(bvis.shape, bvis.nbytes/(1024.**3))

    ti = np.repeat(np.arange(t), bl)
    ant1 = np.tile(ant1, t)
    ant2 = np.tile(ant2, t)
    assert ti.shape == ant1.shape

    benchmark.pedantic(predict_vis, warmup_rounds=2, rounds=10,
                       iterations=5,
                       args=(ti, ant1, ant2),
                       kwargs={'dde1_jones': a1j, 'source_coh': blj, 'dde2_jones': a2j})
                       #args=(ti, ant1, ant2, a1j, blj, a2j, g1j, bvis, g2j))

```

The timing on the master branch commit prior to the PR:

```bash
(afr3test) sperkins@simon-Y700:~/work/ska/code/codex-africanus/africanus/rime/tests$ git checkout  7414bfc3e6c472c32e1856e6aad4d4b51cedc6b5
Previous HEAD position was d4f1244 Optimise summation in coherency jones multiply sum (#143)
HEAD is now at 7414bfc Remove use of @wraps with dask wrapped functions (#142)
(afr3test) sperkins@simon-Y700:~/work/ska/code/codex-africanus/africanus/rime/tests$ py.test -s -v test_benchmark_predict.py 
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0 -- /home/sperkins/venv/afr3test/bin/python3
cachedir: .pytest_cache
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/sperkins/work/ska/code/codex-africanus, inifile: setup.cfg
plugins: benchmark-3.2.2
collected 1 item                                                                                                                                                                                           

test_benchmark_predict.py::test_benchmark_predict_vis (9100, 64, 2, 2) 0.0347137451171875
PASSED


---------------------------------------------------- benchmark: 1 tests ---------------------------------------------------
Name (time in ms)                   Min       Max      Mean  StdDev    Median     IQR  Outliers     OPS  Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------
test_benchmark_predict_vis     422.2635  432.0793  426.5178  3.5570  425.4410  6.1558       3;0  2.3446      10           5
---------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
============================================================================================ 1 passed in 27.99s ============================================================================================
```

and the timing on the master branch after the PR:

```bash
(afr3test) sperkins@simon-Y700:~/work/ska/code/codex-africanus/africanus/rime/tests$ git checkout d4f1244a08e06b343cc82039c64fdc36bf155c83
Previous HEAD position was 7414bfc Remove use of @wraps with dask wrapped functions (#142)
HEAD is now at d4f1244 Optimise summation in coherency jones multiply sum (#143)
(afr3test) sperkins@simon-Y700:~/work/ska/code/codex-africanus/africanus/rime/tests$ py.test -s -v test_benchmark_predict.py 
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0 -- /home/sperkins/venv/afr3test/bin/python3
cachedir: .pytest_cache
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/sperkins/work/ska/code/codex-africanus, inifile: setup.cfg
plugins: benchmark-3.2.2
collected 1 item                                                                                                                                                                                           

test_benchmark_predict.py::test_benchmark_predict_vis (9100, 64, 2, 2) 0.0347137451171875
PASSED


---------------------------------------------------- benchmark: 1 tests ---------------------------------------------------
Name (time in ms)                   Min       Max      Mean  StdDev    Median     IQR  Outliers     OPS  Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------
test_benchmark_predict_vis     426.7744  444.9174  431.7206  5.7586  430.2545  3.9023       2;2  2.3163      10           5
---------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
============================================================================================ 1 passed in 28.28s ============================================================================================
```

**Comment by sjperkins** [comment]
OK here's the source of confusion -- I shouldn't have been including DDE terms in the benchmark as this doesn't trigger the predict_vis case used in crystalball. Note the difference between the script below and the benchmark script in https://github.com/ska-sa/codex-africanus/pull/143#issuecomment-550402971 is setting ``dde1_jones`` and ``dde2_jones`` to ``None``.

```python
import numpy as np
from africanus.rime.predict import predict_vis


def rf(*a, **kw):
    return np.random.random(*a, **kw)


def rc(*a, **kw):
    return rf(*a, **kw) + 1j*rf(*a, **kw)


def test_benchmark_predict_vis(benchmark):
    s = 10
    t = 100
    a = 14
    c = 64
    co = (2, 2)

    ant1, ant2 = (ar.astype(np.int32) for ar in np.triu_indices(a, 1))
    bl = ant1.shape[0]
    r = t * bl

    a1j = a2j = rc((s, t, a, c) + co)
    blj = rc((s, r, c) + co)
    # g1j = g2j = rc((t, a, c) + co)
    bvis = rc((r, c) + co)

    print(bvis.shape, bvis.nbytes/(1024.**3))

    ti = np.repeat(np.arange(t), bl)
    ant1 = np.tile(ant1, t)
    ant2 = np.tile(ant2, t)
    assert ti.shape == ant1.shape

    benchmark.pedantic(predict_vis, warmup_rounds=1, rounds=5,
                       iterations=10,
                       args=(ti, ant1, ant2),
                       kwargs={'dde1_jones': None, 'source_coh': blj, 'dde2_jones': None})
                       #args=(ti, ant1, ant2, a1j, blj, a2j, g1j, bvis, g2j))
```

Benchmark with optimisations

```bash
$ git checkout d4f1244a08e06b343cc82039c64fdc36bf155c83
Previous HEAD position was 7414bfc Remove use of @wraps with dask wrapped functions (#142)
HEAD is now at d4f1244 Optimise summation in coherency jones multiply sum (#143)
$ py.test -s -vvv -k test_benchmark_predict_vis
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.16, pytest-4.6.6, py-1.8.0, pluggy-0.13.0 -- /home/sperkins/venv/afr2test/bin/python2
cachedir: .pytest_cache
benchmark: 3.2.2 (defaults: timer=time.time disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/sperkins/work/ska/code/codex-africanus, inifile: setup.cfg
plugins: benchmark-3.2.2
collected 106 items / 105 deselected / 1 selected                                                                                                                                                          

test_benchmark_predict.py::test_benchmark_predict_vis ((9100, 64, 2, 2), 0.0347137451171875)
PASSED

============================================================================================= warnings summary =============================================================================================
/home/sperkins/venv/afr2test/local/lib/python2.7/site-packages/_pytest/mark/structures.py:335
  /home/sperkins/venv/afr2test/local/lib/python2.7/site-packages/_pytest/mark/structures.py:335: PytestUnknownMarkWarning: Unknown pytest.mark.flaky - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html

-------------------------------------------------- benchmark: 1 tests --------------------------------------------------
Name (time in ms)                  Min      Max     Mean  StdDev   Median     IQR  Outliers      OPS  Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------
test_benchmark_predict_vis     80.8351  87.3980  82.5771  2.7363  81.3227  2.3407       1;1  12.1099       5          10
------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
=========================================================================== 1 passed, 105 deselected, 1 warnings in 6.81 seconds ===========================================================================
```

Benchmark with optimisations


```bash
(afr2test) sperkins@simon-Y700:~/work/ska/code/codex-africanus/africanus/rime/tests$ git checkout  7414bfc3e6c472c32e1856e6aad4d4b51cedc6b5
Previous HEAD position was d4f1244 Optimise summation in coherency jones multiply sum (#143)
HEAD is now at 7414bfc Remove use of @wraps with dask wrapped functions (#142)
(afr2test) sperkins@simon-Y700:~/work/ska/code/codex-africanus/africanus/rime/tests$ py.test -s -vvv -k test_benchmark_predict_vis
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.16, pytest-4.6.6, py-1.8.0, pluggy-0.13.0 -- /home/sperkins/venv/afr2test/bin/python2
cachedir: .pytest_cache
benchmark: 3.2.2 (defaults: timer=time.time disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/sperkins/work/ska/code/codex-africanus, inifile: setup.cfg
plugins: benchmark-3.2.2
collected 106 items / 105 deselected / 1 selected                                                                                                                                                          

test_benchmark_predict.py::test_benchmark_predict_vis ((9100, 64, 2, 2), 0.0347137451171875)
PASSED

============================================================================================= warnings summary =============================================================================================
/home/sperkins/venv/afr2test/local/lib/python2.7/site-packages/_pytest/mark/structures.py:335
  /home/sperkins/venv/afr2test/local/lib/python2.7/site-packages/_pytest/mark/structures.py:335: PytestUnknownMarkWarning: Unknown pytest.mark.flaky - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html

----------------------------------------------------- benchmark: 1 tests ----------------------------------------------------
Name (time in ms)                   Min       Max      Mean   StdDev    Median      IQR  Outliers     OPS  Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------
test_benchmark_predict_vis     532.5261  557.9767  550.1503  10.6260  554.0632  13.6462       1;0  1.8177       5          10
-----------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
========================================================================== 1 passed, 105 deselected, 1 warnings in 35.54 seconds ==========================================================================
```

so the mean speedup is 550/82 ~6.7X. Which is still less than the 8 ~ 16X claims in https://github.com/ska-sa/codex-africanus/pull/143#issuecomment-526231476, but the benchmarking dimensions may have been different or I may have erroneously included the numba compilation times in the original benchmark.

I guess the takehome message is to always post your benchmarking scripts and probably the results of pip freeze when you report such timings.

**Comment by sjperkins** [comment]
I'll try and take a look at the memory issues. I wonder if something has changed between python 2 and 3...

**Pull request merged**
